### ISSUE TITLE
Trees Not Generating

### ISSUE THREAD

**Issue by NielsPilgaard** [superfluke/treetweaker#10]
Hey!

My custom trees are no longer generating, after I added saplings for them. They used generate correctly.
The trees do get created, saplings and all.

Here's my script: https://pastebin.com/p0NdfscQ

I'm hoping it's user error, what do you think? :)

### Versions
- Forge 1.12.2-14.23.5.2808
- treetweaker-1.6.1

**Comment by superfluke** [comment]
Thankfully you have your scripts on github so I was able to figure out what changed. The issue is the meadows biome has the treesPerChunk=0 so tree tweaker assumes it shouldn't try adding any trees there. However, if you use setGenBiome then tree tweaker will ignore the biomes treePerChunk setting. 
So just adding back `livingwood_large_oak.setGenBiome("traverse:meadow");` will fix your issue.

**Comment by NielsPilgaard** [comment]
Thank you very much! I thought that was just a restriction for some reason.

**Comment by Thesola10** [comment]
I'd just like to add, for search engine purposes, that yes, this also applies to generating trees in the Aether, and the biome ID you're looking for is `aether_legacy:aether_highlands`.
